SR_Project/Application/urls.py
from django.conf.urls import url
from . import views

app_name = 'Application'
urlpatterns = [
    url(r'^upload/$', views.upload,name='upload'),
    url(r'^about/$', views.about,name='about'),

]

SR_Project/SR_Project/urls.py
from django.contrib import admin
from django.urls import path
from Application import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('admin/', admin.site.urls),
    url(r'^Application/', include('Application.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SR_Project/Application/models.py
from django.db import models

# Create your models here.

SR_Project/Application/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

SR_Project/Application/views.py
from django.shortcuts import render
from django.http import HttpResponse
from Application.functions import handle_uploaded_file
from Application.forms import UploadFileForm
from django.conf import settings
from django.core.files.storage import FileSystemStorage

def index(request):
    return render(request, 'Application/index.html')
def about(request):
    return render(request,'Application/about.html')

def upload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.FILES)
        fs = FileSystemStorage()
        myfile = request.FILES['file']
        filename = fs.save(myfile.name, myfile)
        # print(type(filename), type(file))
        # return new file
        handle_uploaded_file('media/' + filename)
        return render(request, "Application/download.html", {'output': filename})
    else:
        form = UploadFileForm()
        return render(request, "Application/upload.html", {'form': form})

SR_Project/Application/templates/Application/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Super Resolution</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'Application/sty.css' %}">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">Super Resolution</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link " href="#">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" a href="{% url 'Application:about' %}">About</a>
               </div>
          </div>
        </nav>

<br><br><br><br><br><br><br>
 <p class="p">
We often disregard the fact that 92% of the world’s data was created in the last 3-4 years. The future is nothing less of a data catastrophe. In the future if no solution is developed we might see data blackmarkets, data rationing. Deep learning can help us fight this problem by building intelligent compressors and cryptographers. We use a solution of this niche problem to solve every low speed internet’s consumer’s nightmare. We are no stranger to the situation where we just love a movie but we don’t have access to it’s HD print. Or when we simply switch to low resolution to save our data over the net. We plan to integrate these two concepts together.
</p>
   <div id="particles-js"></div>
   <script src="{% static 'Application/particles.js' %}"></script>
 <script src="{% static 'Application/app.js' %}"></script>


</body>
</html>

SR_Project/Application/templates/Application/download.html
<!DOCTYPE html>
{% load staticfiles %}


<html lang="en">
<head>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Super Resolution</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'Application/sty.css' %}" >
    <script type="text/javascript" src="{% static 'Application/particle.js' %}"></script>
    <script type="text/javascript" src="{% static 'Application/app.js' %}"></script>
    <!--Let browser know website is optimized for mobile-->
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>

         <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">Super Resolution</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" a href="{% url 'Application:upload' %}">About</a>
               </div>
          </div>
        </nav>
            <div id="particles-js"></div>
   <script src="{% static 'Application/particles.js' %}"></script>
 <script src="{% static 'Application/app.js' %}"></script>
         <iframe src="/media/{{output}}" frameborder="0"></iframe>


    <footer class="page-footer teal" style="position:absolute;
   bottom:0;
   width:100%;
   height:60px;">
     <div class="footer-copyright">
            <div class="container ">
            © 2018 Version 1.0
            <a target="_blank" class="grey-text text-lighten-4 right" href="https://github.com/shivamsaboo17/Super-Resolution"><i class="fa fa-github" style="font-size:30px; text-align:center;"></i></a>
            </div>
      </div>
    </footer
    <script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script>
</body>
</html>



<!-- <div class="upload-btn-wrapper">
  <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">Upload the Video</button>
  </form>
</div> -->

SR_Project/Application/templates/Application/index.html
<!DOCTYPE html>
{% load staticfiles %}


<html lang="en">
<head>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
     <link href="https://fonts.googleapis.com/css?family=Raleway:200,100,400" rel="stylesheet" type="text/css" />
    <meta charset="UTF-8">
    <title>Super Resolution</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'Application/sty.css' %}" >
    <script type="text/javascript" src="{% static 'Application/anim.js' %}"></script>
     <script type="text/javascript" src="{% static 'Application/particle.js' %}"></script>
    <script type="text/javascript" src="{% static 'Application/app.js' %}"></script>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>

         <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">Super Resolution</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="justify-content:flex-end;">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'Application:about' %}">About</a>
               </div>
          </div>
        </nav>
         <br><br><br><br><br><br><br><br>
         <h1>
        <span class="txt-rotate"
              data-period="2000"
             data-rotate='[ "High Definition Video Converter." ]'></span>
        </h1>
        <h2>A simple video enhancer based on Sub-Pixel Convolution.</h2>

<a href="{% url 'Application:upload' %}" class="button">Click to Enhance!</a>

            <div id="particles-js"></div>
   <script src="{% static 'Application/particles.js' %}"></script>
 <script src="{% static 'Application/app.js' %}"></script>


</body>
</html>



<!-- <div class="upload-btn-wrapper">
  <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">Upload the Video</button>
  </form>
</div> -->

SR_Project/Application/templates/Application/upload.html
<!DOCTYPE html>
{% load staticfiles %}


<html lang="en">
<head>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Super Resolution</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
<link type="text/css" rel="stylesheet" href="{% static 'Application/sty.css' %}" >
     <script type="text/javascript" src="{% static 'Application/particle.js' %}"></script>
    <script type="text/javascript" src="{% static 'Application/app.js' %}"></script>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>

         <nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-2 col-md-12" >
          <a class="navbar-brand" href="#">Super Resolution</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="justify-content:flex-end;">
            <div class="navbar-nav">
              <a class="nav-item nav-link " href="#">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" a href="{% url 'Application:upload' %}">About</a>
               </div>
          </div>
        </nav>
           <div id="particles-js"></div>
   <script src="{% static 'Application/particles.js' %}"></script>
 <script src="{% static 'Application/app.js' %}"></script>


          <div class="upload-btn-wrapper">
            <form method="POST" class="post-form" enctype="multipart/form-data">
              {% csrf_token %}
              <!-- {{ form.as_p }} -->
              <!-- <p><label for="id_file"></label> -->
                <input type="file" style="position:absolute;top:48%;left: 43%;" name="file" required id="id_file" />
              <!-- <a id='id_file' class="btn-floating btn-large waves-effect waves-light "><i class="material-icons">add</i>
              <input type="file" name="file" required id="id_file" /></a> -->
              <button type="submit" style="position:absolute;top:55%;left: 41%;" class="button" >Upload the Video <i class="material-icons right">file_upload</i></button>
            </form>
        </div>


   <!-- <footer class="page-footer teal" style="position:absolute;
   bottom:0;
   width:100%;
   height:60px;">
     <div class="footer-copyright">
            <div class="container ">
            © 2018 Version 1.0
            <a target="_blank" class="grey-text text-lighten-4 right" href="https://github.com/shivamsaboo17/Super-Resolution"><i class="fa fa-github" style="font-size:30px; text-align:center;"></i></a>
            </div>
      </div>
    </footer
    <script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script> -->
</body>
</html>



<!-- <div class="upload-btn-wrapper">
  <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">Upload the Video</button>
  </form>
</div> -->